version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: MCserver
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "123456789"
      TYPE: SPIGOT
    volumes:

      - ./minecraft-data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
