version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: MCserver
    ports:
      - 25565:25565 # MC Server port
      - 25575:25575 # Rcon Server port
    environment:
      EULA: "TRUE"
      MEMORY: "_G" # Replace the _ by the number of RAM dedicated to the server
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "" #YOURPASSWORD
#      TYPE: SPIGOT (If you want Spigot, remove the # and this commentary.)
    volumes:

      - ./minecraft-data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
